// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvltfmskvfbjnfwrcuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqdmx0Zm1za3ZmYmpuZndyY3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTc0ODUsImV4cCI6MjA3MjMzMzQ4NX0.-L98diy_f9m6jHiEKTZJS4FpG3TRDD-cbVEev56H6nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});